version: "3.9"

services: 
  front:
    container_name: frontend
    image: jtqfrontend
    build: angular/
    ports: 
      - "80:80"
    networks: 
      - local_test
  back:
    container_name: backend
    image: jtqbackend
    build: java/
    networks: 
      - local_test
  reverseproxy:
    container_name: reverse_proxy
    image: reverseproxy
    build: nginx/
    ports:
     - 80:80
    links: 
     - front
     - back
    networks: 
     - local_test
#docker-compose usa una network default, pero mejor hacerla
networks:
  local_test: 
    driver: bridge
  
    
      
    