apiVersion: v1
kind: Pod 
metadata:
  name: frontend
spec:
  containers:
    - image: docker.io/juanromero01/jump_the_queue:frontend
      name: frontend
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 80
        