#deployment frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels: 
        app: frontend
    spec: 
      containers:
      - name: frontend
        #image: docker.io/juanromero01/jump_the_queue:frontend #esta es la version con la build de api
        image: docker.io/juanromero01/jump_the_queue:frontend_v2 #version con build de local/jump the queue#
        #image: docker.io/juanromero01/jump_the_queue:frontend_v3 #version con build de /jumpthequeue
        #image: 127.0.0.1:8082/repository/repo
        imagePullPolicy: 'Always' #esto es para asegurarme de que pullea y no usa una que tenga ya
        resources: {}
        ports:
        - containerPort: 80 

---

#service frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort

---

#deployment backend
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend #depende del pod, ojo
  name: backend #nombre del deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend #depende pod
  strategy: {}
  template:
    metadata:
      labels: 
        app: backend #nombre del pod
    spec: 
      containers:
      - name: backend
        image: docker.io/juanromero01/jump_the_queue:backend 
        #image: 127.0.0.1:8083/repository/minikube
        imagePullPolicy: 'Always'
        resources: {}
        ports:
        - containerPort: 8081

--- 

#service backend
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  type: NodePort

--- 

#ingress 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kubernetes.docker.internal #docker desktop añade a la lista de hosts esto como 127.0.0.1
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
        - path: "/jumpthequeue"
          backend:
            service:
              name: backend
              port:
                number: 8081
          pathType: Prefix



    