apiVersion: v1
kind: Pod 
metadata:
  name: backend
spec:
  containers:
    - image: docker.io/juanromero01/jump_the_queue:backend
      name: backend
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8081